# Generated by Django 5.1.6 on 2025-02-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Kursnomi ')),
            ],
            options={
                'verbose_name': 'Kurs ',
                'verbose_name_plural': 'Kurslar ',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200, verbose_name='Dars nomi ')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Dars sanasi')),
                ('summary', models.TextField(verbose_name='Dars Haqida')),
                ('views', models.IntegerField(verbose_name="Ko'rishlar soni")),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course', verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': 'Dars ',
                'verbose_name_plural': 'Darslar ',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Dars haqida firkingizni qoldiring ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
        ),
    ]
